package com.ghy.WSClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "FacadeWebservice", targetNamespace = "http://webservice.ncplt.cci.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FacadeWebservice {

	/**
	 * 
	 * @param request53
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "hzsNhbFk")
	@WebResult(name = "hzsNhbFkResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "hzsNhbFkResponse")
	public Response hzsNhbFk(@WebParam(name = "request53", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request53")
	Request request53);

	/**
	 * 
	 * @param request18
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "dkxxtjda")
	@WebResult(name = "dkxxtjdaResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "dkxxtjdaResponse")
	public Response dkxxtjda(@WebParam(name = "request18", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request18")
	Request request18);

	/**
	 * 
	 * @param request4
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djdq")
	@WebResult(name = "djdqResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djdqResponse")
	public Response djdq(@WebParam(name = "request4", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request4")
	Request request4);

	/**
	 * 
	 * @param request21
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "hzsjbxx")
	@WebResult(name = "hzsjbxxResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "hzsjbxxResponse")
	public Response hzsjbxx(@WebParam(name = "request21", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request21")
	Request request21);

	/**
	 * 
	 * @param request3
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djddxx")
	@WebResult(name = "djddxxResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djddxxResponse")
	public Response djddxx(@WebParam(name = "request3", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request3")
	Request request3);

	/**
	 * 
	 * @param request56
	 * @return returns com.ghy.WSClient.SoftInfo
	 */
	@WebMethod(action = "softUpdateWs")
	@WebResult(name = "softUpdateWsResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "softUpdateWsResponse")
	public SoftInfo softUpdateWs(
			@WebParam(name = "request56", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request56")
			SoftInfo request56);

	/**
	 * 
	 * @param request47
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "messageGovernmentWs")
	@WebResult(name = "messageGovernmentWsResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "messageGovernmentWsResponse")
	public Response messageGovernmentWs(
			@WebParam(name = "request47", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request47")
			Request request47);

	/**
	 * 
	 * @param registerBean
	 * @return returns com.ghy.WSClient.RegisterRes
	 */
	@WebMethod(action = "registerWs")
	@WebResult(name = "registerWsResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "registerWsResponse")
	public RegisterRes registerWs(
			@WebParam(name = "registerBean", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "registerBean")
			RegisterBean registerBean);

	/**
	 * 
	 * @param request2
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djddcpxx")
	@WebResult(name = "djddcpxxResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djddcpxxResponse")
	public Response djddcpxx(@WebParam(name = "request2", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request2")
	Request request2);

	/**
	 * 
	 * @param request35
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "nhbsyfh")
	@WebResult(name = "nhbsyfhResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "nhbsyfhResponse")
	public Response nhbsyfh(@WebParam(name = "request35", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request35")
	Request request35);

	/**
	 * 
	 * @param request11
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djmnbb")
	@WebResult(name = "djmnbbResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djmnbbResponse")
	public Response djmnbb(@WebParam(name = "request11", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request11")
	Request request11);

	/**
	 * 
	 * @param request36
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "nhbsyxx")
	@WebResult(name = "nhbsyxxResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "nhbsyxxResponse")
	public Response nhbsyxx(@WebParam(name = "request36", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request36")
	Request request36);

	/**
	 * 
	 * @param request12
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djqgxx")
	@WebResult(name = "djqgxxResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djqgxxResponse")
	public Response djqgxx(@WebParam(name = "request12", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request12")
	Request request12);

	/**
	 * 
	 * @param request15
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djtjda")
	@WebResult(name = "djtjdaResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djtjdaResponse")
	public Response djtjda(@WebParam(name = "request15", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request15")
	Request request15);

	/**
	 * 
	 * @param request5
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djfbdjh")
	@WebResult(name = "djfbdjhResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djfbdjhResponse")
	public Response djfbdjh(@WebParam(name = "request5", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request5")
	Request request5);

	/**
	 * 
	 * @param request13
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djsyfh")
	@WebResult(name = "djsyfhResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djsyfhResponse")
	public Response djsyfh(@WebParam(name = "request13", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request13")
	Request request13);

	/**
	 * 
	 * @param request31
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "nhbmr")
	@WebResult(name = "nhbmrResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "nhbmrResponse")
	public Response nhbmr(@WebParam(name = "request31", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request31")
	Request request31);

	/**
	 * 
	 * @param request14
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djsyxx")
	@WebResult(name = "djsyxxResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djsyxxResponse")
	public Response djsyxx(@WebParam(name = "request14", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request14")
	Request request14);

	/**
	 * 
	 * @param request16
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djtzxx")
	@WebResult(name = "djtzxxResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djtzxxResponse")
	public Response djtzxx(@WebParam(name = "request16", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request16")
	Request request16);

	/**
	 * 
	 * @param request17
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djxyda")
	@WebResult(name = "djxydaResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djxydaResponse")
	public Response djxyda(@WebParam(name = "request17", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request17")
	Request request17);

	/**
	 * 
	 * @param request25
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "xzcxdjhxx")
	@WebResult(name = "xzcxdjhxxResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "xzcxdjhxxResponse")
	public Response xzcxdjhxx(@WebParam(name = "request25", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request25")
	Request request25);

	/**
	 * 
	 * @param request46
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "topNewWs")
	@WebResult(name = "topNewWsResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "topNewWsResponse")
	public Response topNewWs(@WebParam(name = "request46", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request46")
	Request request46);

	/**
	 * 
	 * @param request48
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "xianZhenDjHzs")
	@WebResult(name = "xianZhenDjHzsResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "xianZhenDjHzsResponse")
	public Response xianZhenDjHzs(
			@WebParam(name = "request48", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request48")
			Request request48);

	/**
	 * 
	 * @param request52
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "xianZhenJyhddWs")
	@WebResult(name = "xianZhenJyhddWsResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "xianZhenJyhddWsResponse")
	public Response xianZhenJyhddWs(
			@WebParam(name = "request52", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request52")
			Request request52);

	/**
	 * 
	 * @param request26
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "xzcxsnzx")
	@WebResult(name = "xzcxsnzxResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "xzcxsnzxResponse")
	public Response xzcxsnzx(@WebParam(name = "request26", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request26")
	Request request26);

	/**
	 * 
	 * @param request50
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "xianZhenZcWs")
	@WebResult(name = "xianZhenZcWsResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "xianZhenZcWsResponse")
	public Response xianZhenZcWs(
			@WebParam(name = "request50", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request50")
			Request request50);

	/**
	 * 
	 * @param request22
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "jytzgl")
	@WebResult(name = "jytzglResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "jytzglResponse")
	public Response jytzgl(@WebParam(name = "request22", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request22")
	Request request22);

	/**
	 * 
	 * @param request24
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "xzcxdfcf")
	@WebResult(name = "xzcxdfcfResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "xzcxdfcfResponse")
	public Response xzcxdfcf(@WebParam(name = "request24", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request24")
	Request request24);

	/**
	 * 
	 * @param request27
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "zzjh")
	@WebResult(name = "zzjhResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "zzjhResponse")
	public Response zzjh(@WebParam(name = "request27", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request27")
	Request request27);

	/**
	 * 
	 * @param request1
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djbmhz")
	@WebResult(name = "djbmhzResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djbmhzResponse")
	public Response djbmhz(@WebParam(name = "request1", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request1")
	Request request1);

	/**
	 * 
	 * @param request33
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "nhblyjs")
	@WebResult(name = "nhblyjsResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "nhblyjsResponse")
	public Response nhblyjs(@WebParam(name = "request33", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request33")
	Request request33);

	/**
	 * 
	 * @param request6
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djfxcj")
	@WebResult(name = "djfxcjResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djfxcjResponse")
	public Response djfxcj(@WebParam(name = "request6", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request6")
	Request request6);

	/**
	 * 
	 * @param request8
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djhbqdxx")
	@WebResult(name = "djhbqdxxResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djhbqdxxResponse")
	public Response djhbqdxx(@WebParam(name = "request8", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request8")
	Request request8);

	/**
	 * 
	 * @param request23
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "tbch")
	@WebResult(name = "tbchResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "tbchResponse")
	public Response tbch(@WebParam(name = "request23", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request23")
	Request request23);

	/**
	 * 
	 * @param request32
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "nhbms")
	@WebResult(name = "nhbmsResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "nhbmsResponse")
	public Response nhbms(@WebParam(name = "request32", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request32")
	Request request32);

	/**
	 * 
	 * @param request9
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djhtba")
	@WebResult(name = "djhtbaResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djhtbaResponse")
	public Response djhtba(@WebParam(name = "request9", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request9")
	Request request9);

	/**
	 * 
	 * @param request57
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "hzsMyPlants")
	@WebResult(name = "hzsMyPlantsResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "hzsMyPlantsResponse")
	public Response hzsMyPlants(@WebParam(name = "request57", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request57")
	Request request57);

	/**
	 * 
	 * @param request7
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "djggxx")
	@WebResult(name = "djggxxResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "djggxxResponse")
	public Response djggxx(@WebParam(name = "request7", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request7")
	Request request7);

	/**
	 * 
	 * @param request49
	 * @return returns com.ghy.WSClient.Response
	 */
	@WebMethod(action = "pingJiaWs")
	@WebResult(name = "pingJiaWsResponse", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "pingJiaWsResponse")
	public Response pingJiaWs(@WebParam(name = "request49", targetNamespace = "http://webservice.ncplt.cci.org/", partName = "request49")
	Request request49);

}
