package com.ghy.WSClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.ghy.util.StringUtil;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * FacadeWebserviceService service = new FacadeWebserviceService();
 * FacadeWebservice portType = service.getFacadeWebservicePort();
 * portType.hzsNhbFk(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "FacadeWebserviceService", targetNamespace = "http://webservice.ncplt.cci.org/" )
public class FacadeWebserviceService extends Service {

	private final static URL FACADEWEBSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.ghy.WSClient.FacadeWebserviceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ghy.WSClient.FacadeWebserviceService.class.getResource(".");
			url = new URL(baseUrl, StringUtil.getWSURL());
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: '"+ StringUtil.getWSURL() +"', retrying as a local file");
			logger.warning(e.getMessage());
		}
		FACADEWEBSERVICESERVICE_WSDL_LOCATION = url;
	}

	public FacadeWebserviceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FacadeWebserviceService() {
		super(FACADEWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://webservice.ncplt.cci.org/", "FacadeWebserviceService"));
	}

	/**
	 * 
	 * @return returns FacadeWebservice
	 */
	@WebEndpoint(name = "FacadeWebservicePort")
	public FacadeWebservice getFacadeWebservicePort() {
		return super.getPort(new QName("http://webservice.ncplt.cci.org/", "FacadeWebservicePort"), FacadeWebservice.class);
	}

}
